# -*- coding: utf-8 -*-
"""Hands On1:Create Numpy Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cFiAg5gSe4T7f02DsJ59hbr4TJ2KVWyQ
"""

import numpy as np
np.array([1,2,3])

np.array([[1,2,3],[4,5,6]])

