# -*- coding: utf-8 -*-
"""Hands On2:Numpy Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-E_r3tpQkHd5w0m8sTWErdMvyWHdiJM
"""

import numpy as np
np.zeros((2,3))

arr=np.array([[1,2,3],[4,5,6]])
arr

arr.ravel()

arr.reshape((2,3))

brr=np.array([1,5,3,6,2,8])
brr

brr.sort()
brr

crr=np.array([1,2,3,4,5,6,7,8])
crr

crr[2:]

